// Product catalog — mirrors what the client sells on Mercado Livre.
// Placeholders intentionally — user will swap in real images on Shopify.

const formatBRL = (n) => {
  const [r, c] = n.toFixed(2).split(".");
  return { reais: r.replace(/\B(?=(\d{3})+(?!\d))/g, "."), centavos: c };
};

const products = [
  {
    id: "pcyes-mini-pc",
    brand: "Pcyes",
    title: "Mini PC PCyesOne i3 8GB SSD 240GB Windows 11",
    price: 1499,
    oldPrice: 1799,
    discount: "Cupom PIX10",
    installments: { count: 12, value: 124.92, sem_juros: true },
    shipping: "Frete grátis",
    badge: "MAIS VENDIDO",
    badgeStyle: "best",
    rating: 4.8,
    reviews: 312,
    img: "assets/products/pcyes-mini-pc.png",
    tone: "dark",
    hint: "mini pc",
  },
  {
    id: "toner-evolut",
    brand: "Evolut",
    title: "Cartucho de Toner Evolut 105a / 107a — Laser Mono",
    price: 89.9,
    installments: { count: 6, value: 14.98, sem_juros: true },
    shipping: "Frete grátis",
    badge: "FULL",
    badgeStyle: "new",
    rating: 4.9,
    reviews: 1248,
    img: "assets/products/evolut-toner.png",
    tone: "blue",
    hint: "evolut toner",
  },
  {
    id: "epson-wf-c5890",
    brand: "Epson",
    title: "Multifuncional Epson WorkForce Pro WF-C5890 — Color",
    price: 4299,
    installments: { count: 18, value: 238.83, sem_juros: true },
    shipping: "Frete grátis",
    rating: 4.7,
    reviews: 218,
    img: "assets/products/epson-printer.png",
    tone: "neutral",
    hint: "epson printer",
  },
  {
    id: "byqualy-toner",
    brand: "Byqualy",
    title: "Toner Byqualy Compatível TN-3472 / TN-3470 — 12.000 pgs",
    price: 145,
    installments: { count: 6, value: 24.16, sem_juros: true },
    shipping: "Frete grátis",
    rating: 4.6,
    reviews: 2104,
    img: "assets/products/byqualy-toner.png",
    tone: "dark",
    hint: "byqualy toner",
  },
  {
    id: "hp-toner-premium",
    brand: "Premium",
    title: "Toner HP Premium W1105A / 105A Compatível M1132",
    price: 72,
    oldPrice: 95,
    discount: "24% OFF",
    installments: { count: 4, value: 18, sem_juros: true },
    shipping: "Frete grátis",
    badge: "OFERTA",
    badgeStyle: "sale",
    rating: 4.8,
    reviews: 5320,
    img: "assets/products/hp-toner-premium.png",
    tone: "cyan",
    hint: "hp premium toner",
  },
  {
    id: "pcyes-rx550",
    brand: "Pcyes",
    title: "Placa de Vídeo Pcyes RX 550 8GB GDDR5 128-bit",
    price: 899,
    installments: { count: 12, value: 74.92, sem_juros: true },
    shipping: "Frete grátis",
    badge: "GAMER",
    badgeStyle: "new",
    rating: 4.7,
    reviews: 870,
    img: "assets/products/pcyes-gpu.png",
    tone: "neon",
    hint: "pcyes gpu",
  },
  {
    id: "hdmi-vga",
    brand: "PCShop",
    title: "Adaptador HDMI para VGA com Áudio — Conversor Full HD",
    price: 29.9,
    oldPrice: 49,
    discount: "39% OFF",
    installments: { count: 3, value: 9.97, sem_juros: true },
    shipping: "Frete grátis",
    badge: "MAIS VENDIDO",
    badgeStyle: "best",
    rating: 4.8,
    reviews: 3870,
    img: "assets/products/hdmi-vga.png",
    tone: "dark",
    hint: "hdmi to vga",
  },
  {
    id: "ugreen-reader",
    brand: "UGREEN",
    title: "Leitor de Cartão UGREEN USB 3.0 + USB-C — SD / Micro SD",
    price: 89.9,
    installments: { count: 6, value: 14.98, sem_juros: true },
    shipping: "Frete grátis",
    rating: 4.9,
    reviews: 1495,
    img: "assets/products/ugreen-reader.png",
    tone: "dark",
    hint: "ugreen reader",
  },
  {
    id: "hair-styler",
    brand: "Gama",
    title: "Escova Modeladora Rotativa Gama Glamour Smart Rose 1300W",
    price: 299,
    oldPrice: 399,
    discount: "25% OFF",
    installments: { count: 10, value: 29.9, sem_juros: true },
    shipping: "Frete grátis",
    rating: 4.7,
    reviews: 612,
    img: "assets/products/hair-styler.png",
    tone: "orange",
    hint: "hair styler",
  },
  {
    id: "hp-667-duo",
    brand: "HP",
    title: "Kit Cartucho HP 667 Preto + 667 Colorido — Original",
    price: 182.9,
    oldPrice: 219,
    installments: { count: 12, value: 18.11, sem_juros: true },
    shipping: "Frete grátis",
    badge: "MAIS VENDIDO",
    badgeStyle: "best",
    rating: 4.8,
    reviews: 487,
    img: "assets/products/hp-toner-premium.png",
    tone: "cyan",
    hint: "hp 667 kit",
  },
];

const categories = [
  { id: "cartuchos", name: "Cartuchos & Tintas", count: "320+ produtos", icon: "cartridge" },
  { id: "toners", name: "Toners", count: "180+ produtos", icon: "printer" },
  { id: "impressoras", name: "Impressoras", count: "64 produtos", icon: "printer" },
  { id: "placas", name: "Placas de Vídeo", count: "42 produtos", icon: "gpu" },
  { id: "audio", name: "Áudio & Headsets", count: "150+ produtos", icon: "headset" },
  { id: "perifericos", name: "Periféricos", count: "210+ produtos", icon: "keyboard" },
  { id: "redes", name: "Redes & Internet", count: "88 produtos", icon: "network" },
  { id: "armazenamento", name: "Armazenamento", count: "120+ produtos", icon: "storage" },
  { id: "cabos", name: "Cabos & Adaptadores", count: "260+ produtos", icon: "cable" },
  { id: "papel", name: "Papelaria & Mídia", count: "75 produtos", icon: "printer" },
  { id: "ofertas", name: "Ofertas da Semana", count: "Até 40% OFF", icon: "spark" },
  { id: "novidades", name: "Novidades", count: "Recém-chegados", icon: "spark" },
];

const heroSlides = [
  {
    eyebrow: "Tecnologia direto da fábrica",
    title: ["Sua loja de", "tech, sem", "atravessador"],
    accentWord: "tech",
    lead: "Cartuchos, toners, placas de vídeo e periféricos com preço de quem importa direto. Frete grátis a partir de R$ 199.",
    cta: "Comprar agora",
    secondary: "Ver ofertas",
    theme: "green",
    hint: "tech composition",
  },
  {
    eyebrow: "Mês da impressão",
    title: ["Imprima mais,", "pagando", "menos"],
    accentWord: "menos",
    lead: "Cartuchos compatíveis e originais a partir de R$ 36. Compre 3 leve 4 em itens selecionados.",
    cta: "Ver cartuchos",
    secondary: "Ver toners",
    theme: "yellow",
    hint: "printer hero",
  },
  {
    eyebrow: "Setup gamer",
    title: ["Sua build,", "do zero ao", "1080p"],
    accentWord: "1080p",
    lead: "GT 730, RX 550, GTX 1650 e fontes a preço de atacado. Em até 18x sem juros no cartão.",
    cta: "Montar setup",
    secondary: "Ver placas de vídeo",
    theme: "dark",
    hint: "gpu hero",
  },
];

Object.assign(window, { products, categories, heroSlides, formatBRL });

// Extra products to make PLP grid look full
const moreProducts = [
  {
    id: "epson-664-kit", brand: "Epson", title: "Kit Refil Tinta Epson 664 — 4 Cores 100ml",
    price: 89.9, oldPrice: 119, discount: "25% OFF",
    installments: { count: 6, value: 14.98, sem_juros: true },
    shipping: "Frete grátis", rating: 4.8, reviews: 1840,
    badge: "MAIS VENDIDO", badgeStyle: "best",
    tone: "cyan", hint: "ink refill",
  },
  {
    id: "logitech-h111", brand: "Logitech", title: "Headset Logitech H111 P2 com Microfone",
    price: 79.9, installments: { count: 6, value: 13.32, sem_juros: true },
    shipping: "Frete grátis", rating: 4.7, reviews: 2310,
    tone: "dark", hint: "logitech h111",
  },
  {
    id: "tp-link-tl720", brand: "TP-Link", title: "Roteador TP-Link Archer C20 AC750 Dual Band",
    price: 149.9, installments: { count: 10, value: 14.99, sem_juros: true },
    shipping: "Frete grátis", rating: 4.6, reviews: 980,
    tone: "blue", hint: "wifi router",
  },
  {
    id: "kingston-ssd-240", brand: "Kingston", title: "SSD Kingston A400 240GB SATA III",
    price: 159, oldPrice: 199, discount: "20% OFF",
    installments: { count: 12, value: 13.25, sem_juros: true },
    shipping: "Frete grátis", rating: 4.9, reviews: 5630,
    badge: "OFERTA", badgeStyle: "sale",
    tone: "neutral", hint: "ssd drive",
  },
  {
    id: "mouse-multi", brand: "Multilaser", title: "Mouse Gamer Warrior 3200 DPI RGB",
    price: 49.9, installments: { count: 3, value: 16.63, sem_juros: true },
    shipping: "Frete grátis", rating: 4.5, reviews: 1240,
    tone: "neon", hint: "gamer mouse",
  },
  {
    id: "cabo-hdmi-2m", brand: "Genérica", title: "Cabo HDMI 2.0 4K — 2 metros",
    price: 18.9, installments: { count: 2, value: 9.45, sem_juros: true },
    shipping: "Frete grátis", rating: 4.6, reviews: 870,
    tone: "dark", hint: "hdmi cable",
  },
  {
    id: "hub-usb", brand: "Multilaser", title: "Hub USB 3.0 com 4 portas + Cabo extensor",
    price: 35, installments: { count: 3, value: 11.67, sem_juros: true },
    shipping: "Frete grátis", rating: 4.7, reviews: 460,
    tone: "neutral", hint: "usb hub",
  },
  {
    id: "webcam-hd", brand: "Genérica", title: "Webcam Full HD 1080p com Microfone Embutido",
    price: 99.9, oldPrice: 139,
    installments: { count: 10, value: 9.99, sem_juros: true },
    shipping: "Frete grátis", rating: 4.5, reviews: 728,
    badge: "NOVO", badgeStyle: "new",
    tone: "dark", hint: "webcam hd",
  },
  {
    id: "teclado-mec", brand: "Razer", title: "Teclado Mecânico Razer Cynosa V2 RGB",
    price: 349, installments: { count: 12, value: 29.08, sem_juros: true },
    shipping: "Frete grátis", rating: 4.8, reviews: 410,
    tone: "neon", hint: "mech keyboard",
  },
  {
    id: "fonte-500w", brand: "EVGA", title: "Fonte EVGA 500W 80 Plus White",
    price: 289, installments: { count: 12, value: 24.08, sem_juros: true },
    shipping: "Frete grátis", rating: 4.7, reviews: 1190,
    tone: "neutral", hint: "psu 500w",
  },
];

const allProducts = [...products, ...moreProducts];
Object.assign(window, { moreProducts, allProducts });
